version: "3"
services:
  mongo:
    image: "mongo:latest"
  web:
    stdin_open: true
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    volumes:
      - "./node_modules:/usr/src/app/node_modules"
      - ".:/usr/src/app"